### ISSUE TITLE
PyCon India 2021 CFP Announcement Roadmap

### ISSUE THREAD

**Issue by laishawadhwa** [pythonindia/inpycon2021-tasks#10]
- [x] CFP Server Setup
- [x] Review CFP content for blogs and announcements on social media/mailing lists
- [x] Prepare a list of CFP topics/domains (Pycon India 2020: 12 topics)
- [x] Add CFP button on the main website
- [x] Prepare a blog post for CFP (1 or 2)
- [x] 2nd blog post can be about tips on writing a good CFP
- [x] Social media announcements for CFP
- [x] Form the CFP team
- [ ] Good to add tutorial on adding a preview video of the talk
- [x] Mailing list draft to be prepared

**Comment by realslimshanky** [comment]
@laishawadhwa I'm made a plan to upgrade Junction and shared on Zulip, can you please let me know your Zulip username or ping me there using `realslimshanky` so I can tag you to the thread?

**Comment by anistark** [comment]
@realslimshanky The upgrade plan is to be taken separately. Let's not pause CFP process for that.

**Comment by realslimshanky** [comment]
@anistark aren't we going to push updated CFP this year? I was hoping to start fresh since we have time in our hands.

**Comment by raukadah** [comment]
Added a separate issue to track the announcements https://github.com/pythonindia/inpycon2021-tasks/issues/11

**Comment by anistark** [comment]
There's never really enough time. We need to start CFP either way tomorrow. Take your time with the upgrade. @realslimshanky

**Comment by realslimshanky** [comment]
@anistark sure. I'll work on the upgrade on the side and make sure we get there.

**Comment by laisha-wadhwa** [comment]
> @laishawadhwa I'm made a plan to upgrade Junction and shared on Zulip, can you please let me know your Zulip username or ping me there using `realslimshanky` so I can tag you to the thread?

Have pinged on Zulip

**Comment by anistark** [comment]
CFP is now closed. Closing this.
