### ISSUE TITLE
PyCon India 2021 CFP Announcement 

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#11]
Scheduled for **05 March 2021**

## Tasks
- [ ] Junction setup for 2021
- [ ] Social Media announcement
- [ ] Blog post announcement
- [ ] Mailing list announcement 

### Pre 4PM
- [ ] Set up Junction for CFP 2021
- [ ] Verify the contents of Junction
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [ ] Draft the social media announcement  @abhishekmishragithub
- [ ] Add CFP button on main website@abhishekmishragithub
- [ ] Merge the website changes @palnabarun 

### Post 5PM
- [ ] Deploy the blog and the website @palnabarun 
- [ ] Send the social media announcements out  @abhishekmishragithub
- [ ] Announce on mailing list @laishawadhwa
- [ ] Send the announcements to different python local user group mailing list  @realslimshanky

**Comment by abhishekmishragithub** [comment]
Will keep you posted, just saw the issue :P

**Comment by rayandas** [comment]
Social media announcement for CFP announcement: 

We are excited to announce that we’re now opening the CFP for PyCon India 2021. We can't wait to hear all your amazing ideas! The due date is "date"
Learn more: "Blog"

#PyConIndia2021 #Python
"Poster"
{add other meetup groups}

@abhishekmishragithub @raukadah @sayanchowdhury

**Comment by abhishekmishragithub** [comment]
> Social media announcement for CFP announcement:
> 
> We are excited to announce that CFP of PyCon India 2021 is now open. We can't wait to hear all your amazing ideas! The due date is 15th May, 2021.
> Submit your proposals here: https://in.pycon.org/cfp/2021/proposals/
> 
> #PyConIndia2021 #Python
> "Poster"
> {add other meetup groups}
> 
> @abhishekmishragithub @raukadah @sayanchowdhury

LGTM 👍🏼

**Comment by abhishekmishragithub** [comment]
@raukadah here is the PR for the `submit a talk` button on the website.
link: https://github.com/pythonindia/inpycon2021/pull/5

**Comment by raukadah** [comment]
All the tasks related to this issue is done, closing it.
