### ISSUE TITLE
PyCon India 2021 updated dates Announcement

### ISSUE THREAD

**Issue by Sc0rpi0n101** [pythonindia/inpycon2021-tasks#12]
Scheduled for 3rd March 2021

## Tasks
- [ ] PyCon India 2021 Main website updates
- [ ] Social Media announcement
- [ ] Blog post announcement
- [ ] Mailing list announcement

## Pre 4PM
- [ ] Update PyCon India 2021 Main website with new dates @abhishekmishragithub
- [ ] Update the announcement blog with new dates @vipulgupta2048 @Sc0rpi0n101
- [ ] Merge the updated dates blog @vipulgupta2048 @Sc0rpi0n101
- [ ] Draft the social media announcement @abhishekmishragithub
- [ ] Merge the website changes @palnabarun

## Post 5PM
- [ ] Deploy the blog and the website @palnabarun
- [ ] Send the social media announcements out @abhishekmishragithub
- [ ] Announce on mailing list @raukadah
- [ ] Update the announcements to all mailing list @raukadah

**Comment by abhishekmishragithub** [comment]
Social media draft : 

```
Hello Folks, we have made a small change in our conference dates.
The conference will take place from 17th Sept to 20th Sept 2021.
Following is the day-wise schedule for the same.
17th Sept: workshop
18th-19th Sept: Talks
20th Sept: DevSprints

#pyconindia2021 #Python #pyladies #pythonprogramming

```

@sayanchowdhury @raukadah @Sc0rpi0n101, please review.

**Comment by raukadah** [comment]
> Social media draft :
> 
> ```
> Hello Folks, we have made a small change in our conference dates.
> The conference will take place from 17th Sept to 20th Sept 2021.
> Following is the day-wise schedule for the same.
> 17th Sept: Workshops 👩🏻‍💻👨🏻‍💻 
> 18th-19th Sept: Conference talks 🎙️| 
> 20th Sept: DevSprints 💻 
> 
> #pyconindia2021 #Python #pyladies #pythonprogramming
> ```
> 
> @sayanchowdhury @raukadah @Sc0rpi0n101, please review.

Do we also want to include https://in.pycon.org/blog/2021/schedule-update.html in the tweet?

**Comment by rayandas** [comment]
Social media announcement:
Twitter:
https://twitter.com/pyconindia/status/1367105452182364165?s=19
Facebook:
https://www.facebook.com/133849919970392/posts/4084656694889675/
LinkedIn:
https://www.linkedin.com/feed/update/urn:li:activity:6772873411774558208

**Comment by raukadah** [comment]
https://mail.python.org/pipermail/inpycon/2021-March/013152.html email sent and blog published https://in.pycon.org/blog/2021/schedule-update.html

Thanks everyone for working on this.
