### ISSUE TITLE
PyCon India 2021 Communication channels 

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#13]
Scheduled for **05 March 2021**

## Tasks
- [ ] Blog post stating different communication channels
- [ ] Mailing list announcement 

### Pre 4PM
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [ ] Email draft review @realslimshanky
- [ ] Merge the website changes @palnabarun 

### Post 5PM
- [ ] Send the social media announcements out  @abhishekmishragithub
- [ ] Announce on mailing list @realslimshanky
