### ISSUE TITLE
PyCon India 2021 Keynotes names suggestions announcements

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#15]
Scheduled for **07 March 2021**

## Tasks
- [ ] Mailing list announcement 
- [ ] Social Media announcements

### Pre 4PM
- [ ] Draft the email for keynote names suggestion
- [ ] Draft the social media text forkeynote names suggestion

### Post 5PM
- [ ] Send the social media announcements out  @abhishekmishragithub
- [ ] Announce on mailing list @laishawadhwa
- [ ] Send the announcements to different python local user group mailing list  @realslimshanky

**Comment by Sc0rpi0n101** [comment]
I've created an email draft at https://pad.riseup.net/p/inpycon-keynote-suggestions. Please review.

**Comment by realslimshanky** [comment]
@Sc0rpi0n101 Fix a few things, the rest looks good to me.

**Comment by realslimshanky** [comment]
@laishawadhwa I've added your name to the sheet to follow up on the mailing lists, you also have the permission to edit it.
https://docs.google.com/spreadsheets/d/1co9BV2_WrVyJTbKez0CuLphSIz31rpCAlp0DlmLstbU/edit?usp=sharing
cc: @raukadah

**Comment by raukadah** [comment]
Thanks to everyone who worked on it, closing it now
