### ISSUE TITLE
PyCon India 2021 Announcement

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2021-tasks#2]
Scheduled for **25th February 2021**

## Tasks
- [ ] Social Media announcement
- [ ] Blog post announcement
- [ ] Mailing list announcement 

### Pre 4PM
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [ ] Draft the social media announcement @Pradhvan @abhishekmishragithub
- [ ] Merge the website changes @palnabarun 

### Post 5PM
- [ ] Deploy the blog and the website @palnabarun 
- [ ] Send the social media announcements out @Pradhvan @abhishekmishragithub
- [ ] Announce on mailing list @raukadah

**Comment by rayandas** [comment]
We have to change Twitter, Facebook and LinkedIn bios to and add TBA as conference dates maybe? @abhishekmishragithub

**Comment by abhishekmishragithub** [comment]
> We have to change Twitter, Facebook and LinkedIn bios too and add TBA as conference dates maybe? @abhishekmishragithub

Yes, I will update those as well before the announcement. 
Good point @rayandas 👍🏼

**Comment by abhishekmishragithub** [comment]
Took reference from last year. Gonna use it as a thread.

Please review - @sayanchowdhury @rayandas @anistark

`Thread [1/3]
We are back with the 13th edition of PyCon India this time over the internet - online mode,  from 16th - 19th September. More details regarding CFP, tickets, and workshops coming soon. 

https://in.pycon.org/

Thread[2/3]

PyCon India is a volunteer-driven conference and we are looking out of volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. :smile: 

Form Link: [link]

Thread[3/3]

The communication platform for the conference is kept open and is the same as last year.  So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia

Zulip Channel Link: https://pyconindia.zulipchat.com/#narrow/stream/275447-2021.2Fdiscussion`

**Comment by raukadah** [comment]
Thank you @abhishekmishragithub for drafting it down.

> Thread[2/3]
> 
> PyCon India is a volunteer-driven conference and we are looking out of volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. :smile: 
> 
> Form Link: [link]

We will be doing the volunteer announcement tomorrow, so we can save this tweet for tomorrow?

**Comment by Sc0rpi0n101** [comment]
The PR for the blog is https://github.com/pythonindia/inpycon-blog/pull/352

>> https://in.pycon.org/
I think the blog link would be better here. 

>> So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia

How about "Feel free to join our Zulip channel or find us on the Freenode network at #pyconindia to stay up to date with the conference and interact with the community,"?

**Comment by abhishekmishragithub** [comment]
> Thank you @abhishekmishragithub for drafting it down.
> 
> > Thread[2/3]
> > PyCon India is a volunteer-driven conference and we are looking out of volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. 😄
> > Form Link: [link]
> 
> We will be doing the volunteer announcement tomorrow, so we can save this tweet for tomorrow?

Shall i remove the 2nd thread then?
let's have only 1st and 3rd.

**Comment by abhishekmishragithub** [comment]
> The PR for the blog is [pythonindia/inpycon-blog#352](https://github.com/pythonindia/inpycon-blog/pull/352)
> 
> > > https://in.pycon.org/
> > > I think the blog link would be better here.
> 
> > > So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia
> 
> How about "Feel free to join our Zulip channel or find us on the Freenode network at #pyconindia to stay up to date with the conference and interact with the community,"?

Looks good, just need to check the character limit 😄

**Comment by abhishekmishragithub** [comment]
Updated:
```
Thread [1/2]
We are back with the 13th edition of PyCon India this time over the internet - online mode,  from 16th - 19th September. More details regarding CFP, tickets, and workshops coming soon. 

https://in.pycon.org/

Thread[2/2]

The communication platform for the conference is kept open and is the same as last year.  So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia

Zulip Channel Link: https://pyconindia.zulipchat.com/#narrow/stream/275447-2021.2Fdiscussion
```

**Comment by anistark** [comment]
> Took reference from last year. Gonna use it as a thread.
> 
> Please review - @sayanchowdhury @rayandas @anistark
> 
> ```
> Thread [1/3]
> We are back with the 13th edition of PyCon India this time over the internet - online mode,  from 16th - 19th September. More details regarding CFP, tickets, and workshops coming soon. 
> 
> https://in.pycon.org/
> 
> Thread[2/3]
> 
> PyCon India is a volunteer-driven conference and we are looking out of volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. :smile: 
> 
> Form Link: [link]
> 
> Thread[3/3]
> 
> The communication platform for the conference is kept open and is the same as last year.  So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia
> 
> Zulip Channel Link: https://pyconindia.zulipchat.com/#narrow/stream/275447-2021.2Fdiscussion
> ```

If we move the volunteer form tweet to tomorrow, rest can go today. 
👍🏼

**Comment by sayanchowdhury** [comment]
Agreed, volunteer tweet to go tomorrow. Rest looks good.

**Comment by abhishekmishragithub** [comment]
> > The PR for the blog is [pythonindia/inpycon-blog#352](https://github.com/pythonindia/inpycon-blog/pull/352)
> > > > https://in.pycon.org/
> > > > I think the blog link would be better here.
> > 
> > 
> > > > So feel free to interact with the community either in the Zulip chat or on Freenode network #pyconindia
> > 
> > 
> > How about "Feel free to join our Zulip channel or find us on the Freenode network at #pyconindia to stay up to date with the conference and interact with the community,"?
> 
> Looks good, just need to check the character limit 😄

@Sc0rpi0n101, suggested sentence os exceeding the character limit in twitter.
So, I am keeping the initial draft only.

**Comment by Sc0rpi0n101** [comment]
>> @Sc0rpi0n101, suggested sentence os exceeding the character limit in twitter.
So, I am keeping the initial draft only.

Sure

Also, can someone review and merge the blog? It's almost time.
CC: @palnabarun @sayanchowdhury

**Comment by abhishekmishragithub** [comment]
@sayanchowdhury Please close this issue.

**Comment by raukadah** [comment]
Proposal sent: https://mail.python.org/pipermail/inpycon/2021-February/013146.html
