### ISSUE TITLE
PyCon India 2021 Flying Circus Hangout Plan

### ISSUE THREAD

**Issue by bijjybox** [pythonindia/inpycon2021-tasks#29]
## Tasks
 
 **Proposed Dates** 
- 24 Apr 2021
- Sprint wise

**Proposed Platform**
- YT
- Twitter Space
- Google Meet

**Hosts**
- For first event - @abhishekmishragithub @apsychogirl
- Nominate yourself here

 **Social media posts**
- Minimum of 2 posts before event and one post event
- Cross posting on Twitter, IG, Mailing Lists, Reddit, Facebook, LinkedIn @ramkalahasthy @rachejazz @haripriya9647 @shivangdubey @vedant-kakde @rohitsinngh @rayandas
- 1 Blog before event
 
 ### Topics for the hangout (Time Limit - 1 hour)
 * [ ] Past Pycon Experiences
 * [ ] Show & Tell - Bring your own Project
 * [ ] Ice breaker activities
 * [ ] Games (scribble)

**Comment by bijjybox** [comment]
## Flying Circus First event - Scheduled on 24 Apr 2021
**Theme** - Past Pycon Experiences
**Host** - @apsychogirl  + @abhishekmishragithub 
**Platform** - Google Meet Link (meet.google.com/kdo-zgms-pef)
**Speakers** - Yet to be decided 
**Document for the reference** - [Doc](https://docs.google.com/document/d/1gmaFvR83LW9SCOlxxWWRQyJsevELA8azlnibqxsN8hc/edit?usp=sharing)

 ## Tasks 
 Scheduled for 20 Apr 2021
 
* [ ]  Social Media announcement @rachejazz @ramkalahasthy
 * [ ]  Blog post announcement @Sc0rpi0n101 
 * [ ]  Mailing list announcement @shivangdubey
 * [ ]  Speakers for the event @raukadah 

## For Speakers
Feel free to nominate yourself for the Past PyCon Experiences speaker by mentioning your github handles below.

**Comment by Sc0rpi0n101** [comment]
@apsychogirl can you send me some pointers regarding the event or a link to the docs with the details of the event for the blog. 

nvm. Didn't see the doc link in the comment above

**Comment by bijjybox** [comment]
> @apsychogirl can you send me some pointers regarding the event or a link to the docs with the details of the event for the blog.
> 
> nvm. Didn't see the doc link in the comment above

Doc link - https://docs.google.com/document/d/1gmaFvR83LW9SCOlxxWWRQyJsevELA8azlnibqxsN8hc/edit?usp=sharing

Let me know if you need anything else

**Comment by anistark** [comment]
@apsychogirl Any updates here?
