### ISSUE TITLE
PyCon India 2021 Volunteer Announcement - 1

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2021-tasks#3]
Scheduled for **26th February 2021**

## Tasks
- [ ] Social Media announcement
- [ ] Blog post announcement
- [ ] Mailing list announcement 

### Pre 4PM
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [ ] Draft the social media announcement @Pradhvan @abhishekmishragithub
- [ ] Merge the website changes @palnabarun 

### Post 5PM
- [ ] Deploy the blog and the website @palnabarun 
- [ ] Send the social media announcements out @Pradhvan @abhishekmishragithub
- [ ] Announce on mailing list @realslimshanky

**Comment by abhishekmishragithub** [comment]
Draft for social media announcement:

```
PyCon India is a volunteer-driven conference and we are looking out for volunteers who can help out in any way possible. So if you want to be part of the volunteering team do fill out the form. :smile: 

Form Link: https://forms.gle/XHecSriHsQJxUFzW7
```

@sayanchowdhury @raukadah please review.

**Comment by sayanchowdhury** [comment]
Looks good to me @abhishekmishragithub

**Comment by Sc0rpi0n101** [comment]
The Blog PR: https://github.com/pythonindia/inpycon-blog/pull/353

**Comment by abhishekmishragithub** [comment]
Please close this issue, as all the announcements are done. Please find below URL's of the post.

Twitter: https://twitter.com/pyconindia/status/1365276202496270340?s=20
Linkedin: https://www.linkedin.com/posts/pyconindia_pycon-india-2021-volunteer-form-activity-6771042048880582656-fbYD
Facebook: https://www.facebook.com/PyConIndia/posts/4070189523003059
Inpycon mailing list: https://mail.python.org/pipermail/inpycon/2021-February/013149.html

cc: @sayanchowdhury @raukadah

**Comment by abhishekmishragithub** [comment]
@sayanchowdhury please close this.

**Comment by raukadah** [comment]
https://mail.python.org/pipermail/inpycon/2021-February/013149.html email sent .
