### ISSUE TITLE
Outreach Partner Announcement

### ISSUE THREAD

**Issue by rayandas** [pythonindia/inpycon2021-tasks#30]
Scheduled for ~~**9th April 2021**~~ ~~**11th April 2021**~~ 12th April 2021

## Tasks
- [x] Social Media announcement
- [x] Blog post announcement
- [x] Mailing list announcement 

### Pre 4PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @rachejazz @ramkalahasthy
- [x] Merge the website changes (if any) @palnabarun / @sayanchowdhury 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun / @sayanchowdhury 
- [x] Send the social media announcements out @rayandas 
- [x] Announce on mailing list @abhishekmishragithub

**Comment by abhishekmishragithub** [comment]
Updating the target date to 11th April, 2021

**Comment by abhishekmishragithub** [comment]
cc: @sayanchowdhury, @palnabarun

**Comment by rayandas** [comment]
Mail to mailing list: https://mail.python.org/pipermail/inpycon/2021-April/013200.html
Twitter: https://twitter.com/pyconindia/status/1381818240502886410
Facebook: https://www.facebook.com/133849919970392/posts/4202733196415357/
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6787584838225526784
