### ISSUE TITLE
Accepting BoF sessions through CFP

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2021-tasks#31]
## Tasks
- [x] Add a third category of proposals for BoF in Junction
- [ ] Add description about BoF on CFP page
- [ ] Announcement/Request BoF proposal submission (with a blog post??)

**Comment by wavicles** [comment]
A new issue #52  regarding announcement of BoFs and Poster Session is created. Closing this.
