### ISSUE TITLE
PyCon India 2021 Volunteer Announcement - 2

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2021-tasks#4]
Scheduled for **04th March 2021 10:00 AM IST**

## Tasks
- [ ] Social Media announcement
- [ ] Mailing list announcement 

### Pre 4PM
- [ ] Draft the social media announcement @Pradhvan @abhishekmishragithub

### Post 5PM
- [ ] Send the social media announcements out @Pradhvan @abhishekmishragithub
- [ ] Announce on mailing list @raukadah

**Comment by sayanchowdhury** [comment]
This will use the same blog announcement from #3, but with a change in text for the mailing list and the social media announcement.

**Comment by abhishekmishragithub** [comment]
Draft for social media post:

```
Have you ever wished you could contribute or give back to the Python community? Well, here's an awesome opportunity for you to do it with the year's premier conference for the Python programming language, PyCon India 2021.

Fill out this form: https://forms.gle/z9mGmASLWyuRZEvr6 & check out this blog to know more about volunteering: https://in.pycon.org/blog/2021/call-for-volunteers.html

#pyconindia2021 #Python #pyladies #pythonprogramming
```

@sayanchowdhury @raukadah please review.

**Comment by realslimshanky** [comment]
The email has been sent to PyCon India https://mail.python.org/pipermail/inpycon/2021-March/013155.html and PyDelhi https://mail.python.org/pipermail/ncr-python.in/2021-March/001969.html

**Comment by raukadah** [comment]
Thanks People, Closing it now.
