### ISSUE TITLE
PyCon India 2021 CFP Date extension Announcement

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#46]
Scheduled for **05th May 2021 06:00 PM IST**

## Info

The new extended CFP closing date is 22nd May, 2021.

## Tasks
- [x] Blog post announcement
- [x] Mailing list announcement
- [x] Poster Design
- [x] Tweet post
- [x] Instagram Post 

### Pre 4PM

- [x] Blog Post merge @Sc0rpi0n101 
- [x] Mailing list draft @Sc0rpi0n101 
- [x] Poster design @noblebatman 
- [x] Tweet draft @rayandas 
- [x] Instagram and LinkedIn post @rayandas 

### Post 5PM
- [x] Deploy the blog post @palnabarun @sayanchowdhury 
- [x] Tweet and instagram post @rayandas 
- [x] Announce on mailing list @rayandas 
- [x] Email post @laisha

**Comment by rayandas** [comment]
Social media post draft:

```
We are extending the CFP submission deadline for #PyConIndia2021 to help speakers who are currently struggling with the effects of the pandemic in their country.

May 22 at 23:59 IST is the new deadline.

[hashtags]
[poster]
```
on thread two:

```
Join our weekly mentorship calls to get assistance regarding your proposal.
Read more: https://in.pycon.org/blog/2021/announce-mentorship.html
```

**Comment by anistark** [comment]
@rayandas Probably better to start with the pandemic stuff and then say that's why we're postponing. What do you think?

**Comment by rayandas** [comment]
Mailing list email draft:

```
Hello everyone, 

We are extending the CFP submission deadline for PyCon India 2021 to help speakers who are currently struggling with the effects of the pandemic in their country.

May 22 at 23:59 IST is the new deadline.

Read more on our blog. [1]

If you want to get assistance regarding your proposal join our weekly mentorship calls.
Read more: [2]

[1]: https://in.pycon.org/blog/2021/announce-mentorship.html
[2]: {blog link}

**Comment by rayandas** [comment]
> @rayandas Probably better to start with the pandemic stuff and then say that's why we're postponing. What do you think?

@anistark yes sounds good.

**Comment by Sc0rpi0n101** [comment]
PR for the blog: https://github.com/pythonindia/inpycon-blog/pull/365

We should also update the date on the CFP page.

**Comment by anistark** [comment]
- [x] CFP Page updated

**Comment by laishawadhwa** [comment]
Please review

Hello everyone, 
Keeping in mind the current scenario - the sharp and wide 
spread of the pandemic, and the ongoing challenges, we understand that
some people might not have enough time to complete their proposals in time.

So, we are extending the CFP submission deadline for PyCon 
India 2021 to help speakers who are currently struggling with the 
effects of the pandemic in their country.
The new deadline is : May 22 at 23:59 IST

Read more on our blog. [1]

If you want to get assistance regarding your proposal join 
our weekly mentorship calls.

Read more: [2]

[1]: https://in.pycon.org/blog/2021/announce-mentorship.html
[2]: {blog link}

**Comment by raukadah** [comment]
Merged blog: https://github.com/pythonindia/inpycon-blog/commit/2927c8b2464c4bbd3a211f8939d7eee77772d6f5

**Comment by rayandas** [comment]
https://twitter.com/pyconindia/status/1389919477190467585?s=19

https://www.facebook.com/133849919970392/posts/4266538163368193/

https://www.linkedin.com/posts/pyconindia_pyconindia2021-python-cfp-activity-6795686102163427328-A5-1
