### ISSUE TITLE
PyCon India 2021 Website v1 deployment

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#47]
Scheduled for **08th May 2021 06:00 PM IST**

## Info

We need to publish the new website which supports keynotes and ticket booking.

## Tasks
- [x] Merge https://github.com/pythonindia/inpycon2021/pull/7
- [x] Announce the same on social media and mailing list

### Pre 4PM

- [x] Merge https://github.com/pythonindia/inpycon2021/pull/7
- [x] Mailing list draft @Sc0rpi0n101 
- [x] Tweet draft @rayandas 
- [x] Instagram and LinkedIn post @rayandas 

### Post 5PM
- [x] Deploy the https://github.com/pythonindia/inpycon2021/pull/7 @palnabarun @sayanchowdhury 
- [x] Tweet and instagram post @rayandas 
- [x] Announce on mailing list @rayandas

**Comment by SaptakS** [comment]
Work remaining for website deployment:
- [x] Update and include the outreach section (tech team)
- [ ] Update tickets.yml with ticket informations to be released @inovizz 
- [ ] Update outreach.yml with outreach partners informations. @rayandas @abhishekmishragithub

**Comment by SaptakS** [comment]
https://github.com/pythonindia/inpycon2021/pull/7 has all the changes needed from code side for the website to be launched and deployed. @palnabarun will sync and get it merged to `experimental` branch tomorrow.

After that, the people responsible for tickets and outreach need to update `data/tickets.yml` and `data/communities.yml` respectively. For community update, you will also need to upload the image for the outreach partner in `images` folder. 

No code changes should be needed to reflect the data at any point. Each data file has a boolean key `live`. If you want to make any section, for example tickets live, just make the boolean key `live` from `false` to `true` in `data/tickets.yml`

cc @pythonindia/pycon-india-2021-team

**Comment by SaptakS** [comment]
Also the primary and secondary buttons (or links) in the hero section of the website are controlled by `data/hero.yml` and is not tied to the HTML. So at any point you can remove either the primary or secondary button, and/or modify what link the primary/secondary buttons point to and their text.

**Comment by rayandas** [comment]
Social media post:
```
PyCon India 2021 website is live!
Watch this space for exciting new updates in the coming weeks!
https://in.pycon.org/2021/

#PyConIndia2021 #Python
```
[poster]

**Comment by Sc0rpi0n101** [comment]
Mailing list draft, please review

```
Hey folks, 

We hope you all are safe and healthy in these tough times. We are excited to announce that we have deployed v1.0 of the PyCon India website. [1]

Go check it out and if you face any issues or find any bugs, please make sure to file an issue on our repository. [2]

If you have any suggestions or feedback regarding the website, please reply to this email. 

[1]: https://in.pycon.org/2021/
[2]: https://github.com/pythonindia/inpycon2021/issues

Regards, 
PyCon India team
```
