### ISSUE TITLE
PyCon India 2021 Tickets Opening Announcements

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#48]
Scheduled for **08th May 2021 12:00 PM IST**

## Info

We need to open tickets during pyflames event.

## Tasks
- [x] Create ticket type on Townscript
- [x] Update the ticket link on website
- [x] Make sure ticket booking is working
- [ ] Blog post
- [ ] Poster Design
- [ ] Tweet/Instagram/Linkedin Post
- [ ]  Email sent

### Pre 10 AM

- [x] Create the ticket type on TownScript @inovizz 
- [x] Update the ticket type on website @inovizz 
- [x] Verify the ticket booking @inovizz 
- [ ] Merge the blog post @Sc0rpi0n101 
- [ ] Poster Draft @noblebatman 
- [ ] Tweet draft @rayandas 
- [ ] Instagram and LinkedIn post @rayandas
- [ ] Email draft @Sc0rpi0n101  
- [ ] Email draft for townscript @inovizz 

### Post 10 AM
- [ ] Deploy the blog post and ticket changes @palnabarun @sayanchowdhury
- [ ] Verify the ticket url redirect @anistark   
- [ ] Tweet and instagram post @rayandas 
- [ ] Announce on mailing list @rayandas 
- [ ] Email post @pythonindia/inpycon-blog 
- [ ] Send email via townscript @inovizz

**Comment by Sc0rpi0n101** [comment]
Blog PR: https://github.com/pythonindia/inpycon-blog/pull/367#pullrequestreview-654893278

Some information like ticket prices needs to be updated, please comment on the PR with the correct data.

**Comment by sayanchowdhury** [comment]
This is done. Closing the issue.
