### ISSUE TITLE
PyCon India 2021 InKind Sponsors Announcements

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#51]
Scheduled for **15th May 2021 05:00 PM IST**

## Info

We need to open InKind Sponsors.

## Tasks

- [x] Finalize the content of the inkind sponsors
- [x] Google form for inkind sponsors selection
- [ ] Blog post
- [ ] Poster
- [ ] Social media post
- [ ] Emails

### Pre 10 AM

- [x] Add the required info for the blog @inovizz 
- [x] Create the google form for the InKind Sponsors selection @inovizz 
- [x] Blog Post draft @Sc0rpi0n101 
- [x] Poster Design @noblebatman 
- [x] Social Media post draft @rayandas 
- [x] Email Draft @Sc0rpi0n101 

### Post 10 AM

- [x] Test the form @inovizz 
- [x] Deploy the blog post @palnabarun @sayanchowdhury
- [x] Tweet and instagram post @rayandas 
- [x] Announce on mailing list @rayandas 
- [x] Email post @raukadah

**Comment by Sc0rpi0n101** [comment]
Can I get some pointers for what all has been finalized for the InKind sponsorships? The last meeting I joined, stuff was still being planned and discussed.

**Comment by inovizz** [comment]
I'll DM you on WhatsApp or Zulip.

**Comment by raukadah** [comment]
@inovizz @Sc0rpi0n101 Any updates on this? Can we target it by 22nd May, 2021?

**Comment by inovizz** [comment]
@Sc0rpi0n101 - I've provided the required information to you over the email, please take a look and let me know if you need any other details.

**Comment by Sc0rpi0n101** [comment]
Blog link: https://github.com/pythonindia/inpycon-blog/pull/376

**Comment by anistark** [comment]
@inovizz What's happening here? Anywhere in particular we're blocked?

cc: @sayanchowdhury @raukadah @RiteshAgrawal

**Comment by inovizz** [comment]
@anistark - The blog seem to be pending as of now. Once that is done, we can proceed further.

**Comment by inovizz** [comment]
Blog status available here - https://github.com/pythonindia/inpycon-blog/pull/376

**Comment by raukadah** [comment]
https://in.pycon.org/blog/2021/call-for-in-kind-sponsors.html and https://mail.python.org/pipermail/inpycon/2021-June/013239.html It's done. Thank you all.
