### ISSUE TITLE
BoF and Poster Session Announcement

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2021-tasks#52]
Scheduled for **17th May 2021 4:00 PM IST**

## Info

We need to announce the CFP for BoFs and Poster Session.

## Tasks
- [x] Junction setup - Create proposal types for BoF and Poster Session.
- [x] Make sure Proposal submission works on CFP submission page. (Trial submission)
- [x] Add relevent information on CFP Page.
- [x] Information on main website (Info in About page and Submission Button on main page)
- [x] Blog Post
- [x] Poster Design
- [x] Social Media Announcement
- [x] Announcement on mailing lists.

**Comment by wavicles** [comment]
@raukadah Please  add assignees

**Comment by wavicles** [comment]
Refer the docs : Information related to BoF and Poster Session and Important points from discussion in the meeting.
1. [BoFs](https://pad.riseup.net/p/PyConIndia2021-BoF-keep)
2. [Poster Session](https://pad.riseup.net/p/PyConIndia2021-Poster-Session-keep)

**Comment by SaptakS** [comment]
What kind of info is needed in website?

**Comment by Sc0rpi0n101** [comment]
Blog PR: https://github.com/pythonindia/inpycon-blog/pull/370

Please review.

**Comment by wavicles** [comment]
The task is completed.
