### ISSUE TITLE
Announce First Keynote Speaker

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#53]
## Info
Scheduled for May 19th, 2021 at 6 PM.

## Tasks
- [x] Social Media announcement @rayandas 
- [x] Blog post announcement @Sc0rpi0n101 
- [x] Mailing list announcement  @raukadah 
- [x] Website update to display the first keynote speaker.  @SaptakS 

### Pre 5PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @rayandas @abhishekmishragithub 
- [x] Merge the website changes @SaptakS 
- [x] Poster up @noblebatman 
- [x] Email draft @raukadah 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @rayandas @abhishekmishragithub 
- [x] Announce on mailing list @raukadah

**Comment by SaptakS** [comment]
Website is already ready, just need to add keynote speaker in data/keynote_speakers.yml and then change live to true.

**Comment by rayandas** [comment]
Social media post:
```
It's our pleasure to announce Alolita Sharma (@alolita) as the first speaker in the keynote lineup of #PyConIndia2021
Alolita is a Principal Technologist at @awscloud and currently serves on the board of @unicode.
[blog link]
Tickets at: http://bit.ly/pyconindia-tickets
[poster]
```

**Comment by Sc0rpi0n101** [comment]
Blog PR: https://github.com/pythonindia/inpycon-blog/pull/372

**Comment by anistark** [comment]
@palnabarun @sayanchowdhury Need to deploy the [blog PR](https://github.com/pythonindia/inpycon-blog/pull/372) first to get the link to update website PR. ^

**Comment by anistark** [comment]
@noblebatman Please upload the poster for promotion once ready.

**Comment by anistark** [comment]
Website PR is progress: https://github.com/pythonindia/inpycon2021/pull/15

**Comment by anistark** [comment]
Mail list draft: https://pad.riseup.net/p/inpycon21-keynote-1-keep
