### ISSUE TITLE
Publish PyCon India 2021 Schedule

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#83]
**Scheduled Date**: Aug 02nd, 2021

### Tasks **Before 5 PM**
- [x] Send the Pull request of Conference and workshop schedule @kalyan678
- [x] Draft the blogpost @Sc0rpi0n101 @vipulgupta2048 
- [x] Draft the email to be sent to different mailing list @Sc0rpi0n101 @vipulgupta2048 
- [x] Get the poster of schedule sharing with keynote @noblebatman 
- [x] Get the draft tweet and Instagram post @abhishekmishragithub 

### Tasks **Post 5 PM**

- [x] Publish the Schedule @palnabarun 
- [x] Send the tweet @abhishekmishragithub 
- [x] Send the email @raukadah 
- [x] Cross post of multiple mailing list @abhishekmishragithub 
- [x] Track the posting on all social media @raukadah

**Comment by vipulgupta2048** [comment]
On it
