### ISSUE TITLE
In-Kind Sponsor Announcements

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2021-tasks#84]
## Tasks:

- [x] [Design Website Section](https://github.com/pythonindia/inpycon2021/issues/37). @SaptakS 
- [x] Update Website Section. Yaml file. @anistark 
- [x] Create poster design. @noblebatman 
- [x] Create draft blog post content. @Sc0rpi0n101 
- [x] Create draft social media post content. @rayandas 
- [x] Create draft mail content. @anistark 

## Announcements:
- Deploy website and blog @palnabarun 
- Send mail to inpycon Mailling List @raukadah 
- Post on all Social Medias @rayandas 

(Have to do each of the above tasks for all the below ones.)

## In-Kind Sponsors:
- [x] DeepSource
- [x] EPAM
- [x] Fulfil.IO
- [x] IBM Quantum
- [x] Packt
- [x] Innovaccer
- [x] Viprush Technologies (OPC) Pvt Ltd, Nagpur
- [x] Toyota Connected India

**Comment by anistark** [comment]
DeepSource branding assets : https://github.com/deepsourcelabs/brand-assets

**Comment by anistark** [comment]
IBM Quantum Assets
[IBM-Quantum-logos-guide 3.zip](https://github.com/pythonindia/inpycon2021-tasks/files/6985910/IBM-Quantum-logos-guide.3.zip)

**Comment by raukadah** [comment]
Fulfil.IO
<img width="651" alt="Fulfil-Blue-Composite" src="https://user-images.githubusercontent.com/47899089/130644646-2cf45f51-5a72-4ba8-af94-d767d32e0dc7.png">

**Comment by raukadah** [comment]
Viprush
![logo_name](https://user-images.githubusercontent.com/47899089/130664019-53d59ca2-db2f-4874-b8ea-c537175e378d.png)

**Comment by Sc0rpi0n101** [comment]
PR for the blog with first 3 sponsors: https://github.com/pythonindia/inpycon-blog/pull/388

**Comment by anistark** [comment]
[Website Update PR for all in-kind sponsors.](https://github.com/pythonindia/inpycon2021/pull/41)
